### ISSUE TITLE
Movie night - add date here

### ISSUE THREAD

**Issue by olso** [Progressbar/Progressbar-Improvement-Proposal#102]
Link facebook event here : https://www.facebook.com/events/503832893464649/ please edit caption 
Discuss movies here

**Comment by KarinTothova** [comment]
I've found this website with some movies; can u check? https://codeslaw.com/insight/top-10-movies-for-programmers-1037928 

also I think we've been thinkin' about the 14.12.

**Comment by olso** [comment]
@KarinTothova  Maybe we could ask some ppl in cowork for suggestions 🙃

**Comment by KarinTothova** [comment]
We could also make a poll or sth on IG to find out the opinions of others🌝

**Comment by yangwao** [comment]
What about short docs like https://www.youtube.com/watch?v=YwtEUD2crwA&t=830s

**Comment by olso** [comment]
@KarinTothova How is this looking?
