### ISSUE TITLE
Another group blood sampling with mojakrv.com

### ISSUE THREAD

**Issue by yangwao** [Progressbar/Progressbar-Improvement-Proposal#103]
In past we organized session with 
https://www.mojakrv.com
What about next 👩‍🔬🧚👩‍⚕️

**Comment by olso** [comment]
I'd still love to have December 💉
Writing to Karpis rn to see if he is around

**Comment by anettrolikova** [comment]
https://www.facebook.com/events/204082250497400/
https://www.facebook.com/events/575804686215274/
