### ISSUE TITLE
meme for toilets 

### ISSUE THREAD

**Issue by anettrolikova** [Progressbar/Progressbar-Improvement-Proposal#107]
Please send some good meme's so we can put it on walls so everyone can laugh while ' doing their business'

**Comment by anettrolikova** [comment]
https://www.google.sk/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjzh7idudveAhUHblAKHYgpAV4QjRx6BAgBEAU&url=https%3A%2F%2Fwww.pinterest.com%2FPhil_Coding%2Fprogramming-memes%2F&psig=AOvVaw29CRNaCtGd658NfJOXiKuB&ust=1542544600218662

**Comment by anettrolikova** [comment]
http://1.bp.blogspot.com/-FFKyH-P0IpM/U1jYYYbsAEI/AAAAAAAAHk4/1-qtTETRYFM/s1600/Solving+Bugs.jpg

**Comment by anettrolikova** [comment]
https://i1.wp.com/www.hazrpg.co.uk/wp-content/uploads/2016/04/programwhileyouprogram.png?fit=625%2C415&ssl=1

**Comment by olso** [comment]
@anettrolikova Please embed images in future, don't wanna click each one 😉

https://guides.github.com/features/mastering-markdown/ look for images example

**Comment by olso** [comment]
Seems to work
