### ISSUE TITLE
Espresso machine

### ISSUE THREAD

**Issue by wonder-sk** [Progressbar/Progressbar-Improvement-Proposal#121]
It would be nice to have a proper espresso machine in the space. The kind where you just press a button and the coffee is ready in few seconds.

And charging 1 EUR per coffee would recover the cost of buying quite soon :-)

**Comment by maht0rz** [comment]
How about buying a Moccamaster instead? Espresso machine needs a lot of skill and maintanance, to produce a good result. Moccamaster is plug and play, you just need a grinder.

**Comment by olso** [comment]
We now have Delonghi icona, checkout the kitchen :)

thx to @rolandhudak
