### ISSUE TITLE
Meeting room booking system via ical?

### ISSUE THREAD

**Issue by olso** [Progressbar/Progressbar-Improvement-Proposal#30]
Ppl keep asking whether they can use the meeting room

https://calendar.google.com/calendar/embed?src=progressbar.sk_it58g550tqstho0f16r1rt35dc%40group.calendar.google.com&ctz=Europe%2FPrague

**Comment by Ivkaa** [comment]
Or google calendar

**Comment by Ivkaa** [comment]
I created google calendar, but I am not sure where to put the link

**Comment by olso** [comment]
@Ivkaa edited issue, at least here

**Comment by yangwao** [comment]
url to meeting room short link https://bit.ly/progressbar-meeting-room

**Comment by yangwao** [comment]
For now send request to public cowork channel https://t.me/coworkprogressbar
When booking meeting room, send us -> name of meeting, lead of meeting, date, time range.

There will be another issue, where we will tune up process for booking meeting room.
