### ISSUE TITLE
Presentation desk

### ISSUE THREAD

**Issue by olso** [Progressbar/Progressbar-Improvement-Proposal#31]

**Comment by Ivkaa** [comment]
Done 😍thanks @olso ✨

**Comment by olso** [comment]
![img_20180822_175531](https://user-images.githubusercontent.com/7975158/44475208-baf61600-a634-11e8-93bf-65a74bd717e1.jpg)
![img_20180822_175517](https://user-images.githubusercontent.com/7975158/44475209-bb8eac80-a634-11e8-9513-f3f7b35ed114.jpg)
