### ISSUE TITLE
Plant some trees, ask the city to do it, in our neighbourhood

### ISSUE THREAD

**Issue by olso** [Progressbar/Progressbar-Improvement-Proposal#37]
![img_20180823_184748](https://user-images.githubusercontent.com/7975158/44539727-38895700-a705-11e8-9d00-9071582c5f62.jpg)

**Comment by olso** [comment]
https://www.odkazprestarostu.sk/bratislava/podnety/56517/skladka-pri-kosoch

**Comment by Ivkaa** [comment]
this has been fixed https://www.odkazprestarostu.sk/bratislava/podnety/56517/skladka-pri-kosoch

**Comment by olso** [comment]
Its owned by tesco btw 😅

**Comment by Ivkaa** [comment]
I think this issue is out of our reach, Id close it
