### ISSUE TITLE
Current sponsors? Alive? Outdated? Still willing to help?

### ISSUE THREAD

**Issue by olso** [Progressbar/Progressbar-Improvement-Proposal#58]
https://www.progressbar.sk/odkazy

#57

**Comment by olso** [comment]
Why are sponsors like BitPanther not listed?
Can someone gather this list?

**Comment by yangwao** [comment]
@olso listed here https://cowork.progressbar.sk/#/sponsors

actual refineryCMS at progressbar.sk will go away..

**Comment by olso** [comment]
Superseeded by #59
