### ISSUE TITLE
Hang the paintings on the wall

### ISSUE THREAD

**Issue by Ivkaa** [Progressbar/Progressbar-Improvement-Proposal#63]
Hang the paintings we got as a gift on the wall and put on social media

**Comment by olso** [comment]
![fotenka1](https://user-images.githubusercontent.com/7975158/47268932-4584c400-d557-11e8-9215-406fcb9ab3df.jpg)
![fotenka2](https://user-images.githubusercontent.com/7975158/47268933-4584c400-d557-11e8-905c-e55767e81c92.jpg)

Closed by

@Zovi343 @Ivkaa @olso
