### ISSUE TITLE
Rails app upgrade

### ISSUE THREAD

**Issue by ysaito8015** [Progressbar/Progressbar-Improvement-Proposal#64]
I'm Rubist and I can upgrade some rails app.

**Comment by olso** [comment]
We are in process of ditching the current thing, and transferring to something more contributor friendly (https://firebase.google.com/) with a React frontend at https://github.com/Progressbar/web2, but its kind of dead now, not a lot of time to focus on it, but its on our priority list 😎

I tried to talk to https://www.cobot.me/ (it offers everything we need for a cowork) to deal something out, but best they could offer is -25% discount (https://www.cobot.me/community-responsibility)

**Comment by ysaito8015** [comment]
May I join  https://github.com/Progressbar/web2 ?
I have experience developing Vue.js sample application with firebase.
I hope this will help.

**Comment by olso** [comment]
@ysaito8015 this project is not being worked on actively, but this one https://github.com/yangwao/progressbar-coweb is current deployed

**Comment by olso** [comment]
Its in process of moving under pb organization, to make it more visible 😊
