### ISSUE TITLE
Prototype another call room

### ISSUE THREAD

**Issue by yangwao** [Progressbar/Progressbar-Improvement-Proposal#69]
As our space is randomly occupied by various people who do phone calls randomly, it could be problematic for others in space listening phone call of others.

Build fake wall from this https://www.akusticka-pena.cz/zbozi-ceny/lisovane-akusticke-desky/ next to the meeting room? 💪 💃

**Comment by olso** [comment]
Hack the elevator for our use

+Has ventilation
+Almost soundproof (if can be stopped between floors)

**Comment by yangwao** [comment]
Ill estimate costs 
  * wall 
  * zakryt / L / roof 
  * construction

Design is required <3

**Comment by yangwao** [comment]
Boxik serves as temporary call room rn, planing another meeting room.
