### ISSUE TITLE
Rules for coworkers during day

### ISSUE THREAD

**Issue by yangwao** [Progressbar/Progressbar-Improvement-Proposal#71]
Fair user policy for space.

We share big open space, so you need to be respectful to each other to keep same level of comfort for you.

If people have their 🎧 headphones on, try not disturb them, they don't wanna be disturbed. Try message them. You don't wanna be disturbed during your workflow.

If all call rooms are occupied, try to use at least 🎧headphones with microphone and speak quietly. You don't wanna be disturbed by loudly calling persons. Or go to the kitchen / staircase area.

If you are fan of notifications, try mute your phone & notebook sounds You don't wanna be disturbed by other people's notifications and sounds.

**Comment by yangwao** [comment]
We can put it to progressbar-coweb https://github.com/Progressbar/progressbar-coweb/issues/23

**Comment by anettrolikova** [comment]
we should make those & put it up on led panel so everyone can read it immediately after enternig space

**Comment by yangwao** [comment]
At least print it somewhere in space.
Also it would be good to have some visual for this

**Comment by anettrolikova** [comment]
tried to make visual for it & we can print it out
[PB rules.pdf](https://github.com/Progressbar/Progressbar-Improvement-Proposal/files/2593157/PB.rules.pdf)

**Comment by yangwao** [comment]
Perfect 😍
Prolly remove this part 
> if you are not in that
group add yourself by click on this link
https://t.me/coworkprogressba

**Comment by anettrolikova** [comment]
tadaaaa 😍 
[PB rules-QR.pdf](https://github.com/Progressbar/Progressbar-Improvement-Proposal/files/2593184/PB.rules-QR.pdf)

**Comment by anettrolikova** [comment]
[PB rules-QR%2Fnoemojis.pdf](https://github.com/Progressbar/Progressbar-Improvement-Proposal/files/2596388/PB.rules-QR.2Fnoemojis.pdf)

**Comment by anettrolikova** [comment]
[PB rulez.pdf](https://github.com/Progressbar/Progressbar-Improvement-Proposal/files/2596430/PB.rulez.pdf)

**Comment by anettrolikova** [comment]
[PB RULEZ.pdf](https://github.com/Progressbar/Progressbar-Improvement-Proposal/files/2596725/PB.RULEZ.pdf)

**Comment by anettrolikova** [comment]
[PB Rulz.pdf](https://github.com/Progressbar/Progressbar-Improvement-Proposal/files/2596742/PB.Rulz.pdf)
