### ISSUE TITLE
Print new stickers

### ISSUE THREAD

**Issue by yangwao** [Progressbar/Progressbar-Improvement-Proposal#78]
We ran out of stickers.

Print layers
https://github.com/Progressbar/presskit

Print something in range of 100€ ~

Thank you 😍

**Comment by Ivkaa** [comment]
With new logo please

**Comment by yangwao** [comment]
related https://github.com/Progressbar/Progressbar-Improvement-Proposal/issues/80

**Comment by olso** [comment]
#93
