### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by Ivkaa** [Progressbar/Progressbar-Improvement-Proposal#80]
- [ ] update press-kit
- [ ] update places where logo is mentioned

![image](https://user-images.githubusercontent.com/16141183/47504217-15e1fe80-d86c-11e8-8d42-9aa4d362de60.png)

- [ ] Square version
Old one
![image](https://user-images.githubusercontent.com/5887929/47580071-2e2a4a00-d94e-11e8-81a2-ad937acae5a7.png)

May may new
![47580071-2e2a4a00-d94e-11e8-81a2-ad937acae5a7](https://user-images.githubusercontent.com/7975158/47580290-cd4f4180-d94e-11e8-9249-d1e0d9833bbe.png)

- [ ] hexagonal version
![image](https://user-images.githubusercontent.com/5887929/47580144-67fb5080-d94e-11e8-8bb7-fab7bf018f12.png)

**Comment by olso** [comment]
src is here

https://github.com/Progressbar/progressbar-coweb/blob/master/cowork-panel/static/img/progressbar-logo-refresh.svg

and here https://github.com/Progressbar/progressbar-coweb/blob/master/cowork-panel/src/components/ProgressbarLogoRefresh.vue 😂

**Comment by olso** [comment]
![47580071-2e2a4a00-d94e-11e8-81a2-ad937acae5a7](https://user-images.githubusercontent.com/7975158/47580290-cd4f4180-d94e-11e8-9249-d1e0d9833bbe.png)

**Comment by yangwao** [comment]
remembers me gooby/dolan meme.

Anyway, what about make holographic or rainbow background? 🏳️‍🌈🌈 https://github.com/Progressbar/Progressbar-Improvement-Proposal/issues/93
Step out from black 😅

**Comment by Ivkaa** [comment]
My friend Karin could help with this one, Ill try to give her onboarding into the topic

**Comment by olso** [comment]
https://github.com/Progressbar/presskit/tree/master/logo_v1.5

thx to @radkaag
