### ISSUE TITLE
Make holographic stickers

### ISSUE THREAD

**Issue by yangwao** [Progressbar/Progressbar-Improvement-Proposal#93]
![img_20181103_113532](https://user-images.githubusercontent.com/5887929/47951139-e6627e80-df5c-11e8-86f8-1195e6ef458d.jpg)

At Devcon I found it very attractive to look on holographic sticker
Some examples
https://www.etsy.com/market/holographic_sticker

We can use hexagon sticker from https://github.com/Progressbar/presskit set

What needs to be done
* lookup for test samples // request them from vendors
* research for price & quality
* order it

**Comment by anettrolikova** [comment]
https://stickerapp.com/custom-stickers/#! 
100pcs of holo stickers in size 5x5 cm will cost 56$

**Comment by anettrolikova** [comment]
We wanna have the coolest holographic stickers but we need around 70€ for them (200pcs). Kindly looking for sponsors. We want to take some on 35CCC ~ would be great way how to promote our space 🌈

**Comment by Ivkaa** [comment]
![image](https://user-images.githubusercontent.com/16141183/49310319-4148b080-f4de-11e8-8843-ed2c8b1b841e.png)
Soon to be delivered, the design is on presskit

**Comment by yangwao** [comment]
finally

![2018-12-14 15 58 27](https://user-images.githubusercontent.com/5887929/50010260-36e7e580-ffb9-11e8-84d4-ad6b9caf0e02.jpg)
![2018-12-14 15 58 23](https://user-images.githubusercontent.com/5887929/50010261-37807c00-ffb9-11e8-8431-9c3e73fd98c9.jpg)
