### ISSUE TITLE
Birthday reminders for people in our space

### ISSUE THREAD

**Issue by olso** [Progressbar/Progressbar-Improvement-Proposal#94]

**Comment by yangwao** [comment]
Is this still thing? 
I'd rather nurture community in way like connecting demand of coworkers with people looking for new opportunities 🤝

**Comment by anettrolikova** [comment]
Is this really important / useful / meaningful issue ? @olso plz react 😍 cuz I dont think that this is issue that we need to discuss about & can close it
cuz we actually dont have that big comunity that we can have big bday parties and celebrate coworkers bdays...
