### ISSUE TITLE
Unreal Engine Meetup - monthly

### ISSUE THREAD

**Issue by alexhajdu** [Progressbar/Progressbar-Improvement-Proposal#97]
Hey! 
My name is Alex, I'm the founder of Unreal User Group Slovakia -[meetup website]( https://www.meetup.com/Unreal-User-Group-Slovakia/)

Currently I'm running monthly meetups - every first tuesday in the month at 18.00 
I'm looking for cozy space with some refreshment, electricity, maybe projector etc... Usually, there is like 6-12 of us, mainly game developers, programmers, 2D/3D artists etc...

Till now, 0100 campus was our sponsor, so we didn't pay for the space, just for the drinks/food consume.

My question is, if you can imagine hosting such a event in your space. Thanks for your reply.
Alex

**Comment by yangwao** [comment]
Sure, we'd love to host it 🌈🙏🤘👷
If we have free slot in calendar facebook.com/progressbar/events you can have meetup in our space 😍✨💞

**Comment by alexhajdu** [comment]
Our next meetup is planned for 4.12.2018, 18:00 seems like this date is free, right?

**Comment by alexhajdu** [comment]
Also, can I (you) create events for like 6 months in the row? From this December ( maybe we skip in January? )  let's say till June ??

**Comment by alexhajdu** [comment]
Hi @yangwao, please let me know what should I do exactly to create an event in the calendar?

**Comment by yangwao** [comment]
I just noticed our hosts and they will come back to you.
We'd love to host Unreal engine meetup in downtown 😍

**Comment by yangwao** [comment]
Looking forward, 4/12/2018 at 6pm at Dunajska 14 
https://www.facebook.com/events/519493575186378/ 💓🤗
